RegisterBlasrOptions.h
=> add fofn option for reads to help info

rules.mk
=> hack for circular dependency

configure.py, extrautils/makefile, makefile, rules.mk, utils/makefile
=> add -lrt always

ctest/useccsallLargeGenome.t
=> Fix cram tests.

configure.py, makefile
=> No darwin librt

Blasr.cpp, utils/PulseToFasta.cpp, utils/ToAfg.cpp
I didn't run all the cramtests. (They are too slow.) But this builds.
=> Subsequent fix due to RegionAnnotaions/RegionTable/RegionUtils API change.

Blasr.cpp, MappingBuffers.hpp, MappingParameters.h, ReadAlignments.hpp, RegisterBlasrOptions.h, ctest/affineAlign.t
Apparently independent of libcpp changes.
=> Refactoring

Blasr.cpp, include/BlasrAlign.hpp, include/BlasrAlignImpl.hpp, include/BlasrMiscs.hpp, include/BlasrMiscsImpl.hpp
=> More refactoring

Blasr.cpp, include/BlasrUtils.hpp, include/BlasrUtilsImpl.hpp
=> Bam concordant

Blasr.cpp, include/BlasrHeaders.h, include/BlasrUtils.hpp, include/BlasrUtilsImpl.hpp
Blasr should compile with and without pbbam.
Chris, would you please review this? Thanks!
=> Compile without pbbam

Blasr.cpp, LICENSE, iblasr/BlasrAlign.hpp, iblasr/BlasrAlignImpl.hpp, iblasr/BlasrHeaders.h, iblasr/BlasrMiscs.hpp, iblasr/BlasrMiscsImpl.hpp, iblasr/BlasrUtils.hpp, iblasr/BlasrUtilsImpl.hpp, iblasr/MappingBuffers.hpp, iblasr/ReadAlignments.hpp
One license file per repo is enough.
=> Move LICENSE

Blasr.cpp, ctest/dataset.t
Enable concordant for dataset.
Add a cram test for dataset -concordant.
=> Enable concordant for datasets.

cram.mk
Hi Chris, 
Is it proper to add 'cramqu' to cram.mk, which submits cram jobs to sge.  This command is probably only useful for me.
Please just go ahead close it if you don't like this idea. 
Yuan
=> Is this commit proper?

ctest/setup.sh
Change test data directory from /mnt/secondary-siv/testdata to /pbi/dept/secondary/siv/testdata
Update cram test.
=>  update cram test.

Blasr.cpp, extrautils/makefile, iblasr/BlasrAlignImpl.hpp, iblasr/BlasrMiscsImpl.hpp, iblasr/BlasrUtilsImpl.hpp, iblasr/MappingIPC.h, iblasr/MappingParameters.h, iblasr/MappingSemaphores.h, makefile, rules.mk, utils/LoadPulses.cpp, utils/PulseToFasta.cpp, utils/SDPMatcher.cpp, utils/SamFilter.cpp, utils/SamToCmpH5.cpp, utils/SamToM4.cpp, utils/ToAfg.cpp, utils/makefile
Fix more warnings. 
Should work with https://github.com/PacificBiosciences/blasr_libcpp/pull/118
=> More fix warnings

utils/bam2bax/BUILD.txt, utils/bam2bax/makefile, utils/bax2bam/makefile, utils/bax2bam/src/CMakeLists.txt, utils/bax2bam/tests/CMakeLists.txt, utils/makefile
type: cd utils && make bam2bax # to build bam2bax
cd utils && make bax2bam # to build bax2bam
=> Makefile for bam2bax and bax2bam

Blasr.cpp, iblasr/MappingParameters.h, utils/bam2bax/tests/CMakeLists.txt
Support -noSplitSubreads option for .bam and .xml files
=> Polymerase bam support

cram.mk, ctest/deterministic.t
=> add a cram test for deterministic with bam input.

iblasr/BlasrHeaders.h
glibc is everywhere, we probably don't need this, but I kinda care
=> MUSL libc fix + rephrasing for GLIBC

utils/bax2bam/src/Bax2Bam.cpp
=> fixed TotalLength & NumRecords in output DataSetXML (bug 31969)

utils/SAWriter.cpp
#211 also the format style fix
=> Adding a forgiving -h argument hook

utils/bax2bam/README.md
Basic README with command-line usage.
=> Added README

utils/bax2bam/src/Bax2Bam.cpp
Default XML outfile suffix was outdated and not spec-compliant. In addition, the generated DataSet type, metadata…file types, etc. did not reflect the bax2bam mode (e.g. subread, ccs).
=> fixing XML output

utils/bam2bax/tests/cram/bam2bax.t
https://github.com/PacificBiosciences/blasr_libcpp/pull/154
=> cram test for bam2bax holexy

utils/bax2bam/tests/bax2bam.t
=> changed input file for cram test 

ctest/aggressiveIntervalCut.t
to fix regression test of blasr
=> local path for the aggressiveIntervalCut test

utils/bax2bam/tests/src/TestData.h.in, utils/bax2bam/tests/src/test_ccs.cpp, utils/bax2bam/tests/src/test_hqregions.cpp, utils/bax2bam/tests/src/test_polymerase.cpp, utils/bax2bam/tests/src/test_subreads.cpp
=> Fix failed bax2bam tests due to pbBam Version update

iblasr/MappingParameters.h, iblasr/RegisterBlasrOptions.h
=> Eixt if ignoreRegions or ignoreHQRegions is set while query is not HDF
