- configure.py
> optparse is in python2.6, needed for Centos6

- .gitignore
- configure.py
- extrautils/makefile
- makefile
- rules.mk
- utils/makefile
This fixes the problem of building in the source-tree and then building in an external directory.
Internally, see:
http://bugzilla.nanofluidics.com/show_bug.cgi?id=27485
> use vpath instead of VPATH

- Blasr.cpp
- utils/PulseToFasta.cpp
- utils/ToAfg.cpp
Update executables because of modifications to SMRTSequence's access functions.
No change in cramfast results.
> For SMRTSequence API changes

- include/BlasrAlignImpl.hpp
- include/BlasrMiscsImpl.hpp
- include/BlasrUtilsImpl.hpp
- include/ReadAlignments.hpp
But we still cannot build w/out USE_PBBAM.
So this only partly addresses #126.
> Minor fixes for macosx.

- iblasr/RegisterFilterOptions.h
Unlike the rest of `iblasr/*`, RegisterFilterOptions.h is included by a program in `utils/*`. That makes it pseudo public (though still not used outside this package), so it should not have a global using statement.
The non-public headers are in iblasr/ for the purpose of making the parent directory look cleaner. They could be moved safely.
> Remove 'using' from public header.

- README.INSTALL.md
- configure.py
- makefile
./configure.py CXXFLAGS=-g <plus other args...>
This should also handle --no-pbbam better, via NO_PBBAM in `defines.mk`.
* https://github.com/PacificBiosciences/blasr_libcpp/compare/b9e2095...ebc49d4
See PacificBiosciences/blasr_libcpp#78.
> CXXFLAGS for configure.py

- MappingParameters.h
In the past, we didnot have test coverage on the mac and earlier versions
of Mac OS X were not happy with blasr code as well. Now this becomes clang-
-buildable, and the multi-thread in BSD-land of osx seems to be better. As
to the test case, we should have multiple sequences in a query fasta. I am
considering adding my (working) test to the internal p4 or gh repository.
> [issue #136] Removing override of nproc for osx.

- Blasr.cpp
- ctest/dataset.t
- iblasr/MappingParameters.h
Enable -bam and -concordant when input files are datasets.xml
Added cram tests to test blasr taking dataset xml as input with/without -bam -concordant
> Support dataset

- Blasr.cpp
- ctest/bamConcordant.t
- iblasr/BlasrMiscs.hpp
- iblasr/BlasrMiscsImpl.hpp
Blasr should use 'full-pass' subreads as concordant
template if possible. However this info is not available in
subreads.bam. Since we know that the first and last subreads
are less likely to be full-pass, here we changed blasr so that
it avoid using the first and last subreads as concordant
template when input is subreads.bam.
update cram tests for bam concordant.
update libcpp
> Blasr: avoid non-full-pass subreads as concordant template.

- ctest/cigarAdjecentIndels.t
- iblasr/BlasrAlignImpl.hpp
- iblasr/BlasrUtilsImpl.hpp
- iblasr/MappingParameters.h
- iblasr/RegisterBlasrOptions.h
The default behaviour of BLASR has been changed such that  no adjacent indels are allowed in SAM/BAM cigar strings unless -allowAdjacentIndels is ON.
Added a cram test.
> Ajacent indels not allowed in SAM/BAM Cigar string by default

- iblasr/RegisterBlasrOptions.h
-help and -h now prints warnbing about future migration to single/double dash formats in comman line options.
> Warning in help about migration to single/double dash in 3.0.1 release

- ctest/cigarAdjecentIndels.t
- ctest/concordant.t
- iblasr/BlasrAlignImpl.hpp
- iblasr/MappingParameters.h
- iblasr/RegisterBlasrOptions.h
Mean alignment accuracy would increase by 1.5% ~ 2% because all concordant alignments are refined.
Remove an unused and misleading parameter noRefineAlign.  The only parameter for no-refining-alignments should be -noRefineAlignments.
Update cram tests.
> Force refine all concordant alignments unless -noRefineAlignments is ON.

- ctest/bamConcordant.t
- ctest/cigarAdjecentIndels.t
- ctest/concordant.t
- ctest/dataset.t
- ctest/setup.sh
- iblasr/BlasrAlignImpl.hpp
- iblasr/MappingParameters.h
- iblasr/RegisterBlasrOptions.h
This option is OFF by default.
When this option is ON,
* concordant alignments will be refined,
* run time is roughly 15% slower on a lambda movie
* BLASR returns identical mapping intervals, with
slightly better pair-wise alignments, increasing
alignment similarity by 1%~1.5%.
Remove an unused and misleading parameter noRefineAlign.
> Add a bool option -refineConcordantAlignments.

- utils/SDPMatcher.cpp
sdpmatcher is not a production tool
added a new option to sdpmather, its default behaviour should remain the same
just for yli's convenience...
> Add -printSimilarity to sdpMatcher.

- extrautils/makefile
- iblasr/BlasrAlignImpl.hpp
- iblasr/BlasrUtilsImpl.hpp
- makefile
- utils/LoadPulses.cpp
- utils/makefile
The history of this file is obscure by several moves within perforce.
I guess this is just a test or a rarely used utility (?), but this illustrates why eliminating warnings should have a HIGH PRIORITY!
```
LoadPulses.cpp:393:30: warning: equality comparison result unused
nused-comparison]
metricIt->second == false;
~~~~~~~~~~~~~~~~~^~~~~~~~
LoadPulses.cpp:393:30: note: use '=' to turn this equality
comparison into an     assignment
```
I am nearly finished with removing the rest that are found by building blasr with Clang.
> ACTUAL BUG FOUND FROM COMPILER WARNINGS

- utils/bax2bam/src/Bax2Bam.cpp
- utils/bax2bam/src/ConverterBase.h
- utils/bax2bam/tests/src/test_ccs.cpp
- utils/bax2bam/tests/src/test_hqregions.cpp
- utils/bax2bam/tests/src/test_polymerase.cpp
- utils/bax2bam/tests/src/test_subreads.cpp
Added: auto-creation of PBI files(s) for bax2bam output - main BAM and scraps BAM (if applicable).
Fixed: DatasetXML output now also contains all of these child files (PBI files & scraps BAM). 
bugzilla: 29086, 29829
> bax2bam: auto-create PBI files(s) and updated XML output 

- utils/bax2bam/src/IConverter.cpp
- utils/bax2bam/src/Settings.cpp
- utils/bax2bam/src/Settings.h
- utils/bax2bam/src/main.cpp
Brings bax2bam up to compliance with PacBioBam spec v3.0.2 (explicit platform model tag in read groups). bax2bam will assume RS input unless the new "--sequel-input" option is specified.
(bug 30855)
> PacBioBam3.0.2 update

- utils/bax2bam/tests/src/test_ccs.cpp
- utils/bax2bam/tests/src/test_hqregions.cpp
- utils/bax2bam/tests/src/test_polymerase.cpp
- utils/bax2bam/tests/src/test_subreads.cpp
Adding test source code changes I missed in the earlier update to PacBioBAM v3.0.2
> fixed PacBioBAM version number in test code

- utils/bam2bax/src/CMakeLists.txt
- utils/bam2bax/src/Converter.cpp
- utils/bam2bax/src/Converter.h
- utils/bam2bax/src/MetadataWriter.cpp
- utils/bam2bax/src/MetadataWriter.h
- utils/bam2bax/tests/cram/bam2plx.t
The new Converter.h/cpp forgets to enable --metadata option (which mocks metadata.xml). Fix it.
Disable a cram test rejecting old (< 3.0.7b) bam files as input.
> Fix metadata xml

- utils/bam2bax/src/Bam2BaxConverterImpl.hpp
- utils/bam2bax/src/Bam2BaxMain.cpp
- utils/bam2bax/src/Bam2PlxMain.cpp
- utils/bam2bax/src/Converter.cpp
- utils/bam2bax/src/Settings.cpp
- utils/bam2bax/tests/cram/bam2bax.t
- utils/bam2bax/tests/cram/bam2plx.t
bam2plx.t was broken due to a change in the PK value API.  Fixed the
values.  Also removed the old polymerase.bam in favor of the scraps +
subreads file.
> Fix cram tests, remove polymerase.bam options

- makefile
Observed using mobs:
```
make: Entering directory home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/_output/modulebuilds/bioinformatics/ext/pi/blasr/_output/build'
/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/prebuilt.out/3.x/gcc/gcc-4.8.4/libc-2.5/../ccache-3.2.2/bin/g++ -O3
-g -DSHA1_7=\"fbf1205*\"
-std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/_output/modulebuilds/bioinformatics/ext/pi/blasr/_output/deplinks/libblasr/include/blasr/alignment -I/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/_output/modulebuilds/bioinformatics/ext/pi/blasr/_outp …
```
> Run git from SRCDIR

- utils/bax2bam/src/Bax2Bam.cpp
A missing break statement caused subread mode setup to fall through & generate ccs read set XML instead.
@natechols - looks like this should do the trick
> Fixed typo in XML output handling 

- utils/bax2bam/src/ConverterBase.h
- utils/bax2bam/src/Settings.cpp
- utils/bax2bam/src/Settings.h
- utils/bax2bam/src/main.cpp
Allows the creation of BAM files from bax files containing legacy chemistries, while maintaining the strict check enabled by default.
> added --allowUnrecognizedChemistryTriple option to bax2bam

- utils/bam2bax/makefile
- utils/bax2bam/makefile
The fix should come with https://github.com/PacificBiosciences/blasr/wiki/INSTALL-bax2bam-without-using-pitchfork-(not-recommended)
This just covers (an edge case](https://github.com/PacificBiosciences/blasr/issues/245#issuecomment-226976670) when a user  want to install blasr and bax2bam without being able to use pitchfork. 
This should not affect any production build.
This should not affect pitchfork build.
> Update bam2bax/bax2bam makefile for installation without pitchfork

- rules.mk
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129
* https://github.com/PacificBiosciences/blasr/issues/258
* https://github.com/PacificBiosciences/pitchfork/issues/265
> Do not use -isystem when the dir might be /usr/include

- ctest/concordant.t
Changed test out file format from sam to m4 in
order to isolate testing of --concordant option
with testing of --sam file format.
TODO: add tests for --sam, may bring some [deprecated tests](https://github.com/PacificBiosciences/blasr/commit/f30a70a3ed8dc4ac5eeb5b6f12bf7cda5bac11ad) back as needed, see bug25741.t and bamIn.t for details.
TODO: deprecate --cigarUseSeqMatch which is no longer supported.
TODO: document changes in sam format
+ all pacbio QVs (e.g., dq, sq) now displays in sam file
+ Tags XS/XE/YS/YE/XL/XT/XQ have been removed
+ Tags qe/qs been added
+ Tag NM has been changed to nm
+ sam clipping (cigar)
+ Coordinate of sam clipping has been changed from within each subread to within unrolled zmw sequence.
TODO: document that the ```pbalign bax.h5 ref.fasta out.cmp.h5 …
```
> Fix cram tests for --concordant

- ctest/concordant.t
minor: remove spaces in concordant.t.
> fix cram test for --concordant: remove spaces

- utils/bax2bam/src/main.cpp
(A customer had expression confusion as to whether bax2bam would call
CCS, which it doesn't)
> bax2bam: document that ccs mode requires ccs.h5 input

- ctest/useccsallBestN1.t
Add '-h', which will then parse and match the content of the expected file.
> Fix samtools view call on created bam file

- utils/bam2bax/BUILD.txt
- utils/bam2bax/CMakeLists.txt
- utils/bam2bax/makefile
- utils/bam2bax/src/CMakeLists.txt
- utils/bam2bax/tests/CMakeLists.txt
- utils/bax2bam/CMakeLists.txt
- utils/bax2bam/makefile
- utils/bax2bam/src/CMakeLists.txt
- utils/bax2bam/tests/CMakeLists.txt
Fix makefiles as needed to accomodate pbbam wrapping of htslib for bax2bam and bam2bax.
Support both the legacy way of specify prebuilt pbbam and htslibs include and lib, as well as building pbbam (which integrate htslib) as part of CMake from scratch.
Added instructions and examples.
Neither mobs nor pitchfork should be affected by this change.
> Fix makefiles as needed to accomodate pbbam wrapping of htslib.

- utils/bax2bam/src/IConverter.cpp
Part of SAT-529 to get the BAM version header in order and in sync with
other tools.  Delete the hardcoded header override.
> Fix header generated by bax2bam

- ctest/noSplitSubreads.t
- iblasr/MappingParameters.h
- iblasr/RegisterBlasrOptions.h
Fix incorrect read group type in unrolled resequencing.
Deprecate cigarUseSeqMatch option.
> Fix incorrect read group type in unrolled resequencing

- ctest/noSplitSubreads.t
Write intermediate test files as local tmp files.
> Minor: fix cram test noSplitSubreads.t
